### ISSUE TITLE
PrusaSlicer 2.4.0 Convert Issue

### ISSUE THREAD

**Issue by sarvenn** [effgarces/Biqu-Thumbnail-Generator#1]
@effgarces hi,
I switched to PrusaSlicer 2.4 beta 1 (final release version does not work on my PC). I used your standalone scripts. It doesn't work. It still works on PS 2.3.3.
I think an update needed for the script to work with version 2.4, right?

This is the error pop up from PS 2.4.0 beta1
Down line it says, system can not found the file
![image](https://user-images.githubusercontent.com/66178082/147385436-866a46f2-bf9d-41af-87fb-09f2ebed1e28.png)

**Comment by effgarces** [comment]
I modified the previous script to comply with PrusaSlicer 2.4 and both the script and the "compiled" standalone versions are now available. I didn't tested it thoroughly but it seems to be working fine.

**Comment by sarvenn** [comment]
Hi @effgarces ,
I could not find the standalone .exe file in releases section files. Could you help me mate?

Update: I could run the script (.py) with your explanation on Readme section. I am printing at the moment. I will check if it works or not. Before that I will compile a new firmware with Classic thumbnail selection in configuration.h for my TFT35 which works faster on my screen. I will let you know about the outcomes.

![image](https://user-images.githubusercontent.com/66178082/147418302-710a5d69-cdf6-4273-8aa8-972acb8f5732.png)
![image](https://user-images.githubusercontent.com/66178082/147418310-775e715b-ed0e-4878-ae86-07e0cf03a528.png)

**Comment by effgarces** [comment]
Download the  biqu_convert_p24.zip file, it has the exe/standalone version

**Comment by sarvenn** [comment]
> Download the biqu_convert_p24.zip file, it has the exe/standalone version

OMG, how could I miss that! Thanks mate, I will try and give my feedbacks.
I changed my thumbnail parser setting to 0 in my configuration.h for my TFT35 E3 V3.
I will give it a try.
Another issue that I've noticed is when I go to next page in Print Part>SD Card menu then when I turn back to previous page, thumbnails switch with default gcode icon, no more thumbnail icon. I will try to shoot a video for the problem.

**Comment by sarvenn** [comment]
Does it have to be 200x200 or 95x95 (TFT35)?
![image](https://user-images.githubusercontent.com/66178082/147460445-66676cfa-22b2-4663-ae42-151189dc2c2b.png)

**Comment by sarvenn** [comment]
Works perfect again @effgarces.
The only issue I noticed is the second part of my bug report https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2300.

"Another issue is that, when I opne my SD card directory, I see thumbnail, which are OK, I switch to second page of my directory, thumbnails are still ok, but when I switch to first page again, thumbnails are not visible anymore, switch to second page, same thing happens, thumbnails are not visible anymore. When I go back up and enter to SD card directory again, thumbnails are visible again."

Your standalone script gcodes replaces the babystep button as thumbnail icon in printing menu. No issue.
