### ISSUE TITLE
PrusaSlicer g-code preview issue for post proceessed files

### ISSUE THREAD

**Issue by sarvenn** [effgarces/Biqu-Thumbnail-Generator#2]
Files processed with the standalone script can not be opened with PrusaSlicer gcode previever.
The error messege is below.
Is there any solution? 🤞

![Ekran görüntüsü 2022-01-08 100432](https://user-images.githubusercontent.com/66178082/148638729-b141c567-e4b2-4653-86a4-d5ee012905f2.jpg)

**Comment by sarvenn** [comment]
@effgarces hello,
I tried to open the gcode file with vscode. I changed nothing and saved the file. afterwards I was able to open with PrusaSlicer gcode previewer. I tried this several times, really weird.
Could you have the chance to try these things as well?
I couldn't understand what causes this warning to appear. prusaslicer_config=end parameter is included in the file.

**Comment by effgarces** [comment]
I will try to take a look at that in the coming weeks, at the moment my workload doesn't give a lot of free time do dedicate to this project.

**Comment by sarvenn** [comment]
Not a big issue, thought I justed wanted to report it.
It was quite weird that whenever I open the gcode file with VScode and without changing anything, I save the file and I could able to open it with PS gcode viewer.

**Comment by sarvenn** [comment]
I still don't know why or how but I think I found the problem @effgarces.

First, I prepared a gcode file without post processing it, then I prepared the same file with post processing script then compared the codes with VSCode. 
I found that there is a sigle blank line at the end of the gcode file of non processed file, double blank lines at post processed file. When I deleted the extra blank line and tried to open with PS Gcode previewer, it opened without any problem.

So if you could find the code that creates that extra blank line at the end of the gcode file and fix it, problem will be solved either.

However, when I do this, this time when I put this file into a SD card and open the file viewer, then I can not see the thumbnail icon, instead standart gcode file icon in my TFT35, really weird.

Update: I tried this scenario, I open the file with vscode and deleted and created the latest blank line and saved the file. PS gcode viewer opens the file now, but thumbnail is dissappeared in TFT35. Really really weird. I'm totally thrilled.

Update 2: I tried the things above with classic Notepad  as gcode editor. This time thumbnail visibility is not effected whether I delete or add blank lines. With two blank line PS gcode viewer did not open the file, single or no blank lines after the last text line PS gcode previewer opens the file and thumbnail is not gone.
So, as a conclusion thumbnail dissappearance have some unknown realition with the text editor, even I don't change anything (e.g. add and delete a line, at the end file is at the initial state when saved), thumbnail is gone after editing with VSCode, but not with a classic Note Pad.
Double blank line, PS Gcode viewer can not open the file because it can not find "prusaslicer_config = end" parameter at the right place I suppose. ( I still can not explain why PS Gcode viewer opens the file after editing with VSCode just deleting and addind a blank line, in the end there is two blank lines again just like at the beginning).

**Comment by sarvenn** [comment]
![image](https://user-images.githubusercontent.com/66178082/152000993-1a955300-e13f-460b-b377-70f1d2476ac7.png)

**Comment by sarvenn** [comment]
[Desktop.zip](https://github.com/effgarces/Biqu-Thumbnail-Generator/files/7979822/Desktop.zip)
These are two differen objects but no difference at the beginning and end parameters. But you'll see that one of them is corrupted and lost thumbnail visibility. Would you please try it yourself?

**Comment by effgarces** [comment]
Thanks for the analysis, I will see what I can do to fix it.

**Comment by effgarces** [comment]
I just added a fixed version of the script and compiled version,  the preview should now be working properly.

**Comment by sarvenn** [comment]
Thnx mate.

**Comment by sarvenn** [comment]
@effgarces unfortunately I could not open the Zip file because windows defender found virus/trojan in that file :) Could you check the file:  [biqu_convert_p24.zip](https://github.com/effgarces/Biqu-Thumbnail-Generator/releases/download/0.03/biqu_convert_p24.zip)

**Comment by effgarces** [comment]
There's no virus/trojan on the file, but windows defender does complain that the executable is unknown and stops it's execution, all because the file is not signed.

**Comment by sarvenn** [comment]
> There's no virus/trojan on the file, but windows defender does complain that the executable is unknown and stops it's execution, all because the file is not signed.

Alright, I proceeded and if works as it supposed to be. Good job @effgarces , thank you.
I like this post processor. Very user friendly and usefull.
